/**
 * Generated by scripts/gen-cordis-catalog.ts — do not edit by hand; run
 * `pnpm run gen-cordis-catalog` to regenerate (freshness-gated by
 * `pnpm run verify-cordis-catalog` in doc-sync).
 *
 * The dsh-mygo mount-time vocabulary: for every harness event, its
 * dispatch mode, the top-level property names of its real return type, and
 * the discriminant labels of a decision-union return type. Produced by the
 * same AST walk as docs/cordis-catalog and the tool-cordis runtime API, so
 * this data and the rendered docs cannot diverge. The manager validates
 * `reads`/`writes`/`appends` names and intercept `returns` branches against
 * this artifact — no handwritten allowlist.
 *
 * @module @r05en1cu/dsh-mygo/event-vocabulary
 */

/** One harness event's mount-time declaration vocabulary. */
export interface PluginEventVocabularyEntry {
  /** The scoped event name, e.g. `agent/status`. */
  name: string
  /** The dispatch mode from the declaration's `@mode` tag. */
  mode: 'emit' | 'waterfall' | 'parallel' | 'serial'
  /** Top-level property names of the event's real return type, sorted. */
  properties?: readonly string[]
  /** Discriminant labels of a decision-union return type, sorted; empty otherwise. */
  branches?: readonly string[]
}

/** Every harness event's declaration vocabulary, sorted by name. */
export const EVENT_VOCABULARY: readonly PluginEventVocabularyEntry[] = [
  {
    name: 'agent-loop/config-start-failed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/created',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/disposed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/error',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/inbox/claimed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/inbox/discarded',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/inbox/inserted',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/pre-step',
    mode: 'waterfall',
    properties: ['kind', 'messages'],
    branches: ['enter', 'reject'],
  },
  {
    name: 'agent/request',
    mode: 'waterfall',
    properties: ['maxTokens', 'model', 'provider', 'reasoningEffort', 'stop', 'temperature'],
    branches: [],
  },
  {
    name: 'agent/request-error',
    mode: 'waterfall',
    properties: ['kind'],
    branches: ['retry'],
  },
  {
    name: 'agent/session-start',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/status',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'agent/turn-stopping',
    mode: 'serial',
    properties: [],
    branches: [],
  },
  {
    name: 'approval/request',
    mode: 'waterfall',
    properties: [],
    branches: ['allowed-once', 'cancelled', 'rejected', 'unavailable'],
  },
  {
    name: 'commands/change',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'credentials/updated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'domain/changed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'fs/edit-intent',
    mode: 'waterfall',
    properties: ['version'],
    branches: [],
  },
  {
    name: 'fs/observed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'fs/write-intent',
    mode: 'waterfall',
    properties: ['kind', 'version'],
    branches: ['createIfAbsent', 'replaceIfVersion'],
  },
  {
    name: 'goal/changed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'llm/adapters-updated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'llm/stream',
    mode: 'waterfall',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/activated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/deactivated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/disabled',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/enabled',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/installed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/replace-failed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/replaced',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/replacing',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'plugin/uninstalled',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'session/created',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'session/disposed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'session/event',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'session/flush',
    mode: 'parallel',
    properties: [],
    branches: [],
  },
  {
    name: 'settings/document-updated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'settings/updated',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'skills/change',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'subagent/end',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'subagent/provider-added',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'subagent/provider-removed',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'subagent/start',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'system-prompt/assemble',
    mode: 'waterfall',
    properties: ['contexts', 'sections', 'tools', 'variables'],
    branches: [],
  },
  {
    name: 'system-prompt/change',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'telemetry/record',
    mode: 'waterfall',
    properties: ['attributes', 'body', 'channel', 'severity', 'time'],
    branches: [],
  },
  {
    name: 'tools/change',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'tools/code-dispatch-log',
    mode: 'waterfall',
    properties: [],
    branches: [],
  },
  {
    name: 'tools/execute',
    mode: 'waterfall',
    properties: ['additionalContexts', 'concludesTurn', 'content', 'error', 'isError', 'meta', 'value'],
    branches: [],
  },
  {
    name: 'tools/post-execute',
    mode: 'waterfall',
    properties: ['additionalContexts', 'content', 'feedback', 'kind', 'value'],
    branches: ['accept', 'block'],
  },
  {
    name: 'tools/pre-execute',
    mode: 'waterfall',
    properties: ['kind', 'reason'],
    branches: ['allow', 'ask', 'deny'],
  },
  {
    name: 'tools/result',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/agent-end',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/agent-start',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/end',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/log',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/phase',
    mode: 'emit',
    properties: [],
    branches: [],
  },
  {
    name: 'workflow/start',
    mode: 'emit',
    properties: [],
    branches: [],
  },
]
